# - nginx:443,:80
# |- openfire
# |- angular
version: '2.2'
services:
  openfire:
    image: xmpp-grid-broker/openfire
    build:
      context: ./stack/
      dockerfile: Dockerfile
    networks:
      - backend
  angular:
    image: node:8-alpine
    volumes:
      - ./:/mnt
    user: ${UID}
    working_dir: /mnt
    entrypoint: npm run --
    command: ng serve --host 0.0.0.0 --public xgb.localhost.redbackup.org
    networks:
      - backend
  nginx:
    image: fabianhauser/nginx-dehydrated
    volumes:
      - ./stack/nginx:/etc/nginx/sites:ro
      - ./stack/certs/keys/host:/etc/dehydrated/certs:ro
      - ./stack/certs/keys/ca-fullchain.pem:/etc/dehydrated/ca-crt.pem:ro
    ports:
      - 443:443
      - 80:80
    networks:
      - backend
    depends_on:
      - openfire
      - angular
networks:
  backend:

