= Security Recommendations

== Use Content Security Policy (CSP)

The Content Security Policy (CSP) helps to mitigate certain types of attacks such as Cross Site Scripting (XSS) as a second line of defence.
For further information, checkout the https://developer.mozilla.org/en-US/docs/Web/HTTP/CSP[MDN article] and the https://www.w3.org/TR/CSP3/[The W3C Working Draft].

|===
|Header |Value |Notes

|`Content-Security-Policy`
|`default-src 'none'; script-src 'self' 'unsafe-inline'; connect-src 'self' bosh.example.com; img-src 'self'; style-src 'self' 'unsafe-inline';`
| `unsafe-inline` is required by the angular framework.
|`Access-Control-Allow-Origin` |`xgb.example.com bosh.example.com`
|===

== Use a Reverse Proxy for TLS

Proxy the XMPP server with a reverse web proxy that handles TLS authentication (e.g. nginx), to lower the attack surface.

== Verify the Origin Header

Configure the XMPP server to accept only WebSockets/BOSH connections from the origin of the XMPP Broker application.

The `Origin`-Header sent by the Browser must match the domain on which the XMPP Broker application is hosted.
Otherwise, establishing a connection must be blocked.

If the XMPP server used does not support this feature, use a proxy server instead.
